apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: gateway-pool
spec:
  blocks:
    - cidr: 20.0.0.0/32
  serviceSelector:
    matchLabels:
      io.cilium.gateway/owning-gateway: default-gateway
