cluster:
  # Allow the control plane to also be used for scheduling pods
  allowSchedulingOnControlPlanes: true
  network:
    # Disable Flannel CNI so Cilium can instead be used
    cni:
      name: none
  proxy:
    disabled: true
  coreDNS:
    disabled: false
  controlPlane:
    endpoint: https://__VIP_IP__:6443
