# https://artifacthub.io/packages/helm/external-dns/external-dns/1.16.1?modal=values

# Target home-lan CoreDNS not the Talos CoreDNS
extraArgs:
  - --namespace=coredns-lan
provider:
  # https://github.com/kubernetes-sigs/external-dns/blob/master/charts/external-dns/README.md#providers
  name: coredns
serviceMonitor:
  enabled: true
env:
  - name: ETCD_URLS
    valueFrom:
      secretKeyRef:
        name: etcd
        key: ETCD_URL
  - name: ETCD_CA_FILE
    value: /etc/etcd-certs/etcd-ca.crt
  - name: ETCD_CERT_FILE
    value: /etc/etcd-certs/etcd-client.crt
  - name: ETCD_KEY_FILE
    value: /etc/etcd-certs/etcd-client.key
extraVolumes:
  - name: etcd-client-certs-volume
    secret:
      secretName: etcd
extraVolumeMounts:
  - name: etcd-client-certs-volume
    mountPath: /etc/etcd-certs
    readOnly: true
