machine:
  install:
    image: factory.talos.dev/installer/__SCHEMATIC_ID__:__TALOS_VER__
  network:
    hostname: controlplane-worker-__NODE_NUMBER__
    nameservers:
      - 1.1.1.1
      - 1.0.0.1
      - 8.8.8.8
      - 8.8.4.4
    interfaces:
      - interface: eth0
        dhcp: true
        vip:
          ip: __VIP_IP__
