machine:
  features:
    kubePrism:
      enabled: true
      port: 7445
  kubelet:
    # Longhorn support
    extraMounts:
      - destination: /var/lib/longhorn
        type: bind
        source: /var/lib/longhorn
        options:
          - bind
          - rshared
          - rw
