apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflared-token
  namespace: cloudflare
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: aws-secretstore
    kind: ClusterSecretStore
  target:
    name: cloudflared-token
    creationPolicy: Orphan
    deletionPolicy: Retain
  data:
    - secretKey: token
      remoteRef:
        key: cloudflared-token
        property: token
