version: "3"
run: once
vars:
  HARBOR_ADDR: "harbor.okwilkins.dev"
  HARBOR_TOKEN:
    sh: kubectl get secret harbor-dagger-robot-secret -n harbor -o json | jq -r '.data.SECRET' | base64 -d
  HARBOR_ROBOT_USER: "robot$dagger"
  REPO_NAME: "{{.HARBOR_ADDR}}/main"

  COSIGN_PASSWORD:
    sh: kubectl get secret cosign-key-pair -n cosign -o json | jq -r '.data.COSIGN_PASSWORD' | base64 -d
  COSIGN_KEY:
    sh: kubectl get secret cosign-key-pair -n cosign -o json | jq -r '.data."cosign.key"' | base64 -d
  COSIGN_PUB:
    sh: kubectl get secret cosign-key-pair -n cosign -o json | jq -r '.data."cosign.pub"' | base64 -d

  BUILDER_NAME: builder

tasks:
  registry_login:
    desc: Login to Harbor for Docker.
    env:
      HARBOR_TOKEN: '{{.HARBOR_TOKEN}}'
    cmd: echo $HARBOR_TOKEN | buildah login "{{.HARBOR_ADDR}}" -u '{{.HARBOR_ROBOT_USER}}' --password-stdin

  build_push:
    desc: "Buildah builds the image and pushes to a remote repository. Requires that there is a container file in the current directory!"
    dir: "{{.USER_WORKING_DIR}}"
    preconditions:
      - sh: '[ -n "{{.IMG_NAME}}" ]'
        msg: IMG_NAME is empty!
      - sh: '[ -n "{{.TAG}}" ]'
        msg: TAG is empty!
    vars:
      IMG: "{{.REPO_NAME}}/{{.IMG_NAME}}"
      FULL_IMG_NAME: "{{.IMG}}:{{.TAG}}"
    cmds:
      - echo "{{.IMG}}"
      - buildah build --tag {{.FULL_IMG_NAME}}
      - "echo \"Build completed. Digest: $(jq -r '.\"containerimage.digest\"' /tmp/buildx-metadata.json)\""

  cosign_sign:
    desc: Cosign sign by digest (recursive) for all manifests.
    env:
      COSIGN_PASSWORD: '{{.COSIGN_PASSWORD}}'
      COSIGN_KEY: '{{.COSIGN_KEY}}'
      COSIGN_PUB: '{{.COSIGN_PUB}}'
      DIGEST:
        sh: jq -r '."containerimage.digest"' /tmp/buildx-metadata.json
    vars:
      IMG: "{{.REPO_NAME}}/{{.COMPONENT}}:{{.TAG}}"
    cmds:
      - echo "Signing {{.IMG}} @ ${DIGEST}"
      - |
        cosign sign \
          --new-bundle-format=false \
          --use-signing-config=false \
          --yes \
          --key env://COSIGN_KEY \
          --recursive \
          {{.IMG}}@${DIGEST}

  publish:
    desc: "Orchestrate build, push and sign a container"
    cmds:
      - task: docker_login
      - task: build_push
        vars: {COMPONENT: "{{.COMPONENT}}", TAG: "{{.TAG}}", CONTEXT: "{{.CONTEXT}}", BUILD_ARGS: "{{.BUILD_ARGS}}"}
      - task: cosign_sign
        vars: {COMPONENT: "{{.COMPONENT}}", TAG: "{{.TAG}}"}

