apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harbor-admin-credentials
  namespace: harbor
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-secretstore
    kind: ClusterSecretStore
  target:
    name: harbor-admin-credentials
    creationPolicy: Orphan
    deletionPolicy: Retain
  data:
    - secretKey: HARBOR_ADMIN_USERNAME
      remoteRef:
        key: harbor/harbor-admin-credentials
        property: HARBOR_ADMIN_USERNAME
    - secretKey: HARBOR_ADMIN_PASSWORD
      remoteRef:
        key: harbor/harbor-admin-credentials
        property: HARBOR_ADMIN_PASSWORD
