apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harbor-image-pull-robot-secret
  namespace: harbor
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-secretstore
    kind: ClusterSecretStore
  target:
    name: harbor-image-pull-robot-secret
    creationPolicy: Orphan
    deletionPolicy: Retain
  data:
    - secretKey: ROBOT_PASSWORD
      remoteRef:
        key: harbor/image-pull
        property: ROBOT_PASSWORD
