apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: terraform-robot-secret
  namespace: harbor
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-secretstore
    kind: ClusterSecretStore
  target:
    name: terraform-robot-secret
    creationPolicy: Orphan
    deletionPolicy: Retain
  data:
    - secretKey: SECRET
      remoteRef:
        key: harbor/terraform-robot-secret
        property: HARBOR_ADMIN_USERNAME
