apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Gateway API CRDs v1.3.0
  - https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/refs/tags/v1.3.0/config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
  - https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/refs/tags/v1.3.0/config/crd/standard/gateway.networking.k8s.io_gateways.yaml
  - https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/refs/tags/v1.3.0/config/crd/standard/gateway.networking.k8s.io_grpcroutes.yaml
  - https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/refs/tags/v1.3.0/config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
  - https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/refs/tags/v1.3.0/config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml
  - https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/refs/tags/v1.3.0/config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
  # Gateways and routes
  - ./gateways/default.yaml
  - ./gateways/cloudflare.yaml
  - ./http-routes/grafana.yaml
  - ./http-routes/argocd.yaml
  - ./http-routes/prometheus.yaml
  - ./http-routes/excalidraw.yaml
  - ./http-routes/argo-workflows.yaml
  - ./http-routes/harbor-portal.yaml
  # Reference grants
  - ./reference-grants/default-gateway-argocd-tls.yaml
  - ./reference-grants/default-gateway-grafana-tls.yaml
  - ./reference-grants/default-gateway-prometheus-tls.yaml
  - ./reference-grants/default-gateway-draw-tls.yaml
  - ./reference-grants/default-gateway-workflows-tls.yaml
  - ./reference-grants/default-gateway-harbor-tls.yaml
