# https://artifacthub.io/packages/helm/longhorn/longhorn/1.8.1?modal=values

persistence:
  reclaimPolicy: Retain
preUpgradeChecker:
  # https://github.com/longhorn/longhorn/issues/8707
  jobEnabled: false
defaultSettings:
  defaultReplicaCount: 2
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
