apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    password: AgB7YbcQs3e9t7uMigdojA2fx101UBJHeXOxvAmd2pLdi66VuEtxSgKcKjdFzO/dnKaoZzVsKgHM+5qHt3e87SkiIGRpZBcRJOb5i4iFXSmIpuhEh/4lGmYGG19ux5F4xlGGQE1cYxIpKcL6wYCYj3dGgapXV0haRkDxZlhsJXqf5KV2MA8KCpQVIA5oVnQd6Vif0FW5hZuIAe1Ox75MFb+WOk3z81qPL5KYgXps45Eew1OG1stmZgEJ9vs2axBwKMWzLnXDbKIJp0KBUsPx1br+pFShrJQIDq1kvBhryci5VLuiWmcENi/kQAsn+e9v/DMaC1WJoZMVT71Gqxpdh/KxbRuN1FEJOQMcgqQ8SO7vXYfcA5GSvNXiHxvab5YGtzojqdRcgFTU7QBzONMQrm6WCKRDvyTii31CyzeSOdiekkDOqtJ7k4te8oJDmXQDnmFzNPs3qpSEkgfnVPTj55+OSW5DofSfGV642twI5YBqrL/P+joXWYm76Y6vK0bDwuL7w4rX85W+fvd9lQ1Fjle0vd/jTuAgD+9noVxT1J6OsSfQQunriEe94HHPTJzaznUbzNqXyw9n0kRvFS6KdGK124aV3iuGs5w5Nj/t7djJZxptm6X1q57871PtGOjzcBEKQa6AXITZSxP9D1hLM8Ypc+inrYdPPmhlt8E8xf41PojSyeOXub+f4ON056RN+RprxI2IJIcGD911EZtnULEF
    username: AgCYyfQTyjrs5lIwXaAT0h8QPASvkp/97XIwEkOH2DcuK4xwmKW/0u7QDByVlDmn8R2V+dR+Awcey9aRJnxR8UU0qpVPEbi85Xw9kRgFq8pBm5IhL+u8V3jg4Z7JlYk5OfLVit9owWfH4HbXZOq9Y9xoOnT+9uCr47ec3GYoLgfiEr24+A4RygDCEB4HmcpxDumd3vr9rd3WadA5BMBKV7CBTNio1L0MpEIL0yqXBRR7BbqNIKFqA02f2GDxJm2BIAIphYcBUaxquwNHZlu5Q0wUget1H/l1wPJfx/oyG77A6H2Va8599T5YxXwgioaMS70g+TuuVT6D2BRaxeCJjFKBZMpARPfhOzKF4XKFRQxJmbIPp9/sAvwVQnvoetwOWGF/SiE/U7QLZSV/BETAXgjYiFjNdrSuCooG11rPgUgXaJqFfM8aDfDkp0UaCEw1tnznqKwZvSu+/geSb5WJxnNtg7CPd1w18Qcanty8zJIE/JhnRGdvsiySfrBE8c1EQR1rEJT0SpdtpBqQK00dvEUr7mnrVUhNxFukmMt6sJeGoMmnBC69KNeMbTM4ZhlXYKVgkOkZQhztQkmLf5sH1haA8lxxBnvWDDfji+LfL+MubBad6J1pJf+GzIt0ahozgE6F+4vNvLyZuUJoR/b326X9wfSR5nj78Cb6X4Jmbmo7t1RaoKP07/kRBbz9qSdI6ZQHBlOSPg==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: monitoring
