apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cosign
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/okwilkins/h8s
    targetRevision: HEAD
    path: security/cosign/environments/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: cosign
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - PruneLast=true
