apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cosign-key-pair
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-secretstore
    kind: ClusterSecretStore
  target:
    name: cosign-key-pair
    creationPolicy: Orphan
    deletionPolicy: Retain
  data:
    - secretKey: COSIGN_PASSWORD
      remoteRef:
        key: cosign/key-pair
        property: COSIGN_PASSWORD
    - secretKey: cosign.key
      remoteRef:
        key: cosign/key-pair
        property: cosign.key
    - secretKey: cosgin.pub
      remoteRef:
        key: cosign/key-pair
        property: cosign.pub
