apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-workflows-ui-user-read-only
  namespace: argo-workflows
rules:
  # K8s standard APIs
  - apiGroups:
      - ""
    resources:
      - events
      - pods
      - pods/log
    verbs:
      - get
      - list
      - watch
  # Argo APIs see: https://github.com/argoproj/argo-workflows/blob/v3.6.7/manifests/cluster-install/workflow-controller-rbac/workflow-aggregate-roles.yaml
  - apiGroups:
      - argoproj.io
    resources:
      - workflows
      - workflows/finalizers
      - workfloweventbindings
      - workfloweventbindings/finalizers
      - workflowtemplates
      - workflowtemplates/finalizers
      - cronworkflows
      - cronworkflows/finalizers
      - clusterworkflowtemplates
      - clusterworkflowtemplates/finalizers
      - workflowtaskresults
      - workflowtaskresults/finalizers
    verbs:
      - get
      - list
      - watch
