apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-workflows-ui-user-read-only
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-workflows-ui-user-read-only
subjects:
  - kind: ServiceAccount
    name: argo-workflows-ui-user-read-only
    namespace: argo-workflows
