apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia-grafana-client-secret
  namespace: authelia
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-secretstore
    kind: ClusterSecretStore
  target:
    name: authelia-grafana-client-secret
    creationPolicy: Orphan
  data:
    - secretKey: client-secret-hash
      remoteRef:
        key: authelia/grafana-oidc
        property: client-secret-hash
