apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia-hmac-secret
  namespace: authelia
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-secretstore
    kind: ClusterSecretStore
  target:
    name: authelia-hmac-secret
    creationPolicy: Orphan
    deletionPolicy: Retain
  data:
    - secretKey: hmac-secret
      remoteRef:
        key: authelia/hmac-secret
        property: hmac-secret
