apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./encryption-key-secret.yaml
  - ./user-password-secret.yaml
  - ./users-database-configmap.yaml
  - ./session-secret.yaml
  - ./hmac-secret.yaml
  - ./oidc-rsa-key.yaml
  - ./grafana-client-secret.yaml
  - ./argocd-client-secret.yaml
