apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia-user-password
  namespace: authelia
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-secretstore
    kind: ClusterSecretStore
  target:
    name: authelia-user-password
    creationPolicy: Orphan
    deletionPolicy: Retain
  data:
    - secretKey: hash
      remoteRef:
        key: authelia/user-okwilkins-password-hash
        property: hash
