# https://artifacthub.io/packages/helm/argo/argo-cd/7.9.0?modal=values

global:
  domain: argocd.okwilkins.dev
controller:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
server:
  config:
    url: https://argocd.okwilkins.dev
  # As HTTPS is dealt with with Cloudflared, internally use HTTP
  extraArgs:
    - --insecure
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
repoServer:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
applicationSet:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
redis:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
dex:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
notifications:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
