apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: chhoto-url-secret
  namespace: chhoto-url
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-secretstore
    kind: ClusterSecretStore
  target:
    name: chhoto-url-secret
    creationPolicy: Orphan
    deletionPolicy: Retain
  data:
    - secretKey: password
      remoteRef:
        key: chhoto-url/chhoto-url-secret
        property: password
