apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: chhoto-url
  name: chhoto-url
  namespace: chhoto-url
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chhoto-url
  template:
    metadata:
      labels:
        app: chhoto-url
    spec:
      imagePullSecrets:
        - name: harbor-credentials
      containers:
        - name: chhoto-url
          image: harbor.okwilkins.dev/docker-hub-cache/sintan1729/chhoto-url:7.1.2
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - "ALL"
