apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: renovate-github-app-key
  namespace: renovate
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: renovate-github-app-key
    creationPolicy: Owner
  data:
    - secretKey: PRIVATE_KEY
      remoteRef:
        key: renovate/github-app
        property: private-key
