apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-github-app-key
  namespace: renovate
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-secretstore
    kind: ClusterSecretStore
  target:
    name: renovate-github-app-key
    creationPolicy: Orphan
    deletionPolicy: Retain
    template:
      data:
        PRIVATE_KEY: '{{ .private_key | b64dec }}'
  data:
    - secretKey: private_key
      remoteRef:
        key: renovate/github-app
        property: private-key
