apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: longhorn-system
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
