apiVersion: v1
kind: ConfigMap
metadata:
  name: glance-config
  namespace: glance
  labels:
    app: glance
    kubernetes.io/name: glance
data:
  glance.yml: |
    server:
      proxied: true

    branding:
      app-name: Feed

    pages:
      - name: Home
        hide-desktop-navigation: true
        columns:
          - size: full
            widgets:
              - type: search
                search-engine: https://search.okwilkins.dev/search?q={QUERY}
                new-tab: true
                autofocus: true
                placeholder: Search...

              - type: rss
                title: selfh.st
                limit: 10
                collapse-after: 5
                feeds:
                  - url: https://selfh.st/rss/
