apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: glance-oidc-secret
  namespace: glance
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-secretstore
    kind: ClusterSecretStore
  target:
    name: glance-oidc-secret
    creationPolicy: Orphan
  data:
    - secretKey: client-secret-plaintext
      remoteRef:
        key: authelia/glance-oidc
        property: client-secret-plaintext
