apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-cookie-secret
  namespace: glance
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-secretstore
    kind: ClusterSecretStore
  target:
    name: oauth2-cookie-secret
    creationPolicy: Orphan
  data:
    - secretKey: cookie-secret
      remoteRef:
        key: oauth2-proxy/glance-cookie-secret
        property: cookie-secret
