apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: proxmox-hosts-file
  namespace: coredns-lan
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-secretstore
    kind: ClusterSecretStore
  target:
    name: proxmox-hosts-file
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: hosts
      remoteRef:
        key: kubernetes-homelab/proxmox/hosts-file
        property: hosts
