apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: default-gateway
  namespace: default
  annotations:
    lbipam.cilium.io/ips: 1.0.0.0
    io.cilium/lb-ipam-ips: 1.0.0.0
spec:
  gatewayClassName: cilium
  infrastructure:
    annotations:
      io.cilium/lb-ipam-ips: 1.0.0.0
  addresses:
    - type: IPAddress
      value: 1.0.0.0
  listeners:
    - protocol: HTTP
      port: 8080
      name: web
      allowedRoutes:
        namespaces:
          from: All
