apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cnpg-terraform-backend-prod-app-user-credentials
  namespace: terraform
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-secretstore
    kind: ClusterSecretStore
  target:
    name: cnpg-terraform-backend-prod-app-user-credentials
    creationPolicy: Orphan
    deletionPolicy: Retain
  data:
    - secretKey: username
      remoteRef:
        key: cnpg/cnpg-terraform-backend-prod-app-user-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: cnpg/cnpg-terraform-backend-prod-app-user-credentials
        property: password
