# INFO: Duplicate of the secret found here: storage/harbor/environments/prod/dagger-robot-secret.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harbor-dagger-robot-secret
  namespace: dagger-workflows
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-secretstore
    kind: ClusterSecretStore
  target:
    name: harbor-dagger-robot-secret
    creationPolicy: Orphan
    deletionPolicy: Retain
  data:
    - secretKey: SECRET
      remoteRef:
        key: harbor/dagger-robot-secret
        property: SECRET
