# https://artifacthub.io/packages/helm/fluent/fluent-bit-collector/1.0.6?modal=values

config:
  pipeline:
    inputs:
      - name: tail
        path: /var/log/containers/*.log
        tag: kube.*
        skip_long_lines: true
        refresh_interval: 5

      - name: tail
        path: /var/log/audit/kube/*.log
        tag: audit.*
        parser: json
        skip_long_lines: true
        refresh_interval: 5
        mem_buf_limit: 5MB

    filters:
      - name: kubernetes
        match: kube.*

    outputs:
      - name: loki
        match: "*"
        host: loki.monitoring.svc.cluster.local
        uri: /loki/api/v1/push
        port: 3100

serviceMonitor:
  enabled: true

podSecurityContext:
  fsGroup: 1000

securityContext:
  runAsNonRoot: true
  runAsUser: 1000

containerSecurityContext:
  capabilities:
    add:
      - DAC_READ_SEARCH

extraVolumes:
  - name: audit-logs
    hostPath:
      path: /var/log/audit/kube

extraVolumeMounts:
  - name: audit-logs
    mountPath: /var/log/audit/kube
    readOnly: true

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    memory: 256Mi

dashboards:
  enabled: true
