apiVersion: v1
kind: ConfigMap
metadata:
  name: corefile-coredns
  namespace: coredns-lan
data:
  Corefile: |-
    .:53 {
        errors
        health {
            lameduck 5s
        }
        ready
        log . {
            class error
        }
        prometheus :9153

        hosts /blocklist/hosts {
            fallthrough
        }
        loop
        reload
        loadbalance
    }
