apiVersion: v1
kind: ConfigMap
metadata:
  name: corefile-coredns
  namespace: coredns-lan
data:
  Corefile: |-
    okwilkins.dev:53 {
        errors
        health {
            lameduck 5s
        }
        log . {
            class error
        }
        kubernetes cluster.local
        k8s_external okwilkins.dev
        loop
        loadbalance
    }
    .:53 {
        errors
        health {
            lameduck 5s
        }
        ready
        log . {
            class error
        }
        prometheus :9153
        hosts /blocklist/hosts {
          fallthrough
        }
        forward . 1.1.1.1 1.0.0.1
        loop
        reload
        loadbalance
    }
