apiVersion: v1
kind: ConfigMap
metadata:
  name: corefile-coredns
  namespace: coredns-lan
data:
  Corefile: |-
    okwilkins.dev:53 {
        ready
        log . {
            class error
        }
        template IN A {
            match (^|\.)okwilkins\.dev\.$
            answer "{{ .Name }} 60 IN A 192.168.1.121"
            fallthrough
        }
        template IN AAAA {
            match (^|\.)okwilkins\.dev\.$
            rcode NXDOMAIN
            fallthrough
        }
        errors
    }
    .:53 {
        health {
            lameduck 5s
        }
        ready
        log . {
            class error
        }
        prometheus :9153
        hosts /blocklist/hosts {
          fallthrough
        }
        forward . tls://1.1.1.1 tls://1.0.0.1 {
          tls_servername cloudflare-dns.com
          next NXDOMAIN
        }
        forward . tls://8.8.8.8 tls://8.8.4.4 {
          tls_servername dns.google
        }
        loop
        reload
        loadbalance
        errors
    }
