apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    password: AgBWA9k/Jy317BvILhg2i+zno/h7lougQhu+dyHRsKi1xAevxDYI/o7+Kig94Sj52QeMRMdCWRX7ZtBUnWPrPCyT1gEuYkHuY3V2ujMGV9q45ivqFXDo3cpdDFeYINKh7cj7KPVp552PdfQ/GgOGrzq5INcx8r0pLjz40vGpG5hgZR1Rk3ng0sHSjSqR9auoZGxZJIxkwJqTeWr8WPzNKe2YdGxz7EXR6i5eR0HY/E2PaeEorqZ4facTVTLNzg81D6vi4fxuwZiYrrLL3a6YXtfr444oScLv1pWnykrYtiy2AYviwnUdkwA98deYWG3u6PMr3FJt7kKvxCpOq8m8sD8tSOO1KkMtJsiqLApyqfMmAlfGhqzGlZKsSie3zS8hY4fAQOaEgt4xVfzNTmwo4MIaVACda8ryWOMC44W8tHDQLnsLrP+pvT9dm/o2h8vdYl2+7BZUms6+EgD+vofynNpyftA6N2MFl3w8gahSGheUhaPZOVtNebDLVn7Tk0BPoPX0sW+FXXjidGIrlwdlpBT5spAmhwgHKyXa/DUPziNSunz3yoqTuUtnGtGmMq18z86+1lWtLqS9crkJmWj9RGPnt65l/NppWHmfLBFLgL9wT+kxyLHXp8Xc0JRXtEBv/NhwICCeH+Gr+gF1tfPCOKau5LpLDmfMu1VfThpnrOR/q3ikXUfUzXJCJpqpdmfPYJecPzDIkaItzQFESEcy6JFW
    username: AgBD6eC4eWe7wAGMiXOojGa1UenILbRVb1Jk9hthWjv2o0W9o7TzSB2OJG+MX6uKDZY7LOzeCUesCoM8JEpcBz9h42CjH3J72D5S62JW/MP1B6MFKTzVW2o1WLryGc/bD0W+pqZOnn7RX1OSX1IlVvaTFQC56ljL4EDPyF3bo3S9mUxUkWznOsnGlXFrAm/wnPwaOZprUkI82VfOP6YVh7YPywlrv0p2AY5vv9WQbIBlLHcMrqSUpByGIiRfplDEWcqZoKQ6DmPE15Dc+UMM6cr1ZKgNg1ysYleOXwodXPH0LefM/4savMUQWOKmDFT1t8yXt6YJ7w3dBpQJfyvf7aB+Qp6GbRv/5iWF6MJMMhZChdhBvl3ZhMLZM17okEQGymLkQKNjquUV+29Tw+p7pn+TWZASC4JgU1RjkiZ+AAJ1zBUQvp5UZNUli9Zx7GxxjW+W30QyztOVe7nTYKZZw9U3FcFxq3Zp5zK6iXtsAxfJ88p+AC6j2DS2TdiirZKPZ5fAXAIvxTgrFi9+KYgKzcaI3NUxkvEnQbxx/ToHXahFYyK+MZO+yZZhgYaKd/pwJld7hFJEiz8Wf9axdM2xh6FnAQhiN44nNSnednK5ZwgxiqTSEesfmbFz7B+//OTyh1K2pmH2b9ZxnW1nu5f3d51Wom8Ahvv7YhPToGQqk4FVljOUCRwaIvFBGlDIRt9HQgYd14rigw==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: monitoring
