# https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack/71.2.0?modal=values 

namespaceOverride: monitoring
grafana:
  admin:
    existingSecret: grafana-admin
    userKey: username
    passwordKey: password
persistence:
  enabled: true
  type: sts
  accessModes:
    - ReadWriteOnce
  size: 20Gi
  finalizers:
    - kubernetes.io/pvc-protection
