apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pocket-id-encryption-key
  namespace: pocket-id
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-secretstore
    kind: ClusterSecretStore
  target:
    name: pocket-id-encryption-key
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: ENCRYPTION_KEY
      remoteRef:
        key: pocket-id/encryption-key
        property: ENCRYPTION_KEY
