apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: pocket-id
  name: pocket-id
  namespace: pocket-id
spec:
  serviceName: pocket-id
  replicas: 1
  selector:
    matchLabels:
      app: pocket-id
  template:
    metadata:
      labels:
        app: pocket-id
    spec:
      imagePullSecrets:
        - name: harbor-credentials
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: pocket-id
          image: harbor.okwilkins.dev/ghcr-cache/pocket-id/pocket-id:v2.4.0
          imagePullPolicy: IfNotPresent
          # https://pocket-id.org/docs/configuration/environment-variables
          env:
            - name: APP_URL
              value: "https://auth.okwilkins.dev"
            - name: TRUST_PROXY
              value: "true"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: ANALYTICS_DISABLED
              value: "true"
            - name: DB_CONNECTION_STRING
              value: "/app/data/pocket-id.db"
            - name: ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: pocket-id-encryption-key
                  key: ENCRYPTION_KEY
          volumeMounts:
            - name: pocket-id-data
              mountPath: /app/data
            - name: tmp-volume
              mountPath: /tmp
          ports:
            - name: http
              containerPort: 1411
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          livenessProbe:
            httpGet:
              port: http
              path: /healthz
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              port: http
              path: /healthz
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 256Mi
      volumes:
        - name: tmp-volume
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: pocket-id-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
