apiVersion: v1
kind: Secret
metadata:
  name: vault-cert-manager-issuer-token
  namespace: cert-manager
  annotations:
    kubernetes.io/service-account.name: vault-issuer
type: kubernetes.io/service-account-token
