---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: default
spec:
  encryptedData:
    password: AgA2WNTEw2uoNyybzpgvKy7bHVVgSMUP7wLpgz4nMXNvEllYmMGiMejvlfGYpG8GZhx7hNpVQRLD2rJA8uQDK9g6Cfj2aBsx/Zdz6rRdw/wsFLji1DBmQJq4Rvyl41BjSEa8i8m9V1b/tDCXPzQ3BAhRU40yz59akmHI4ntVSZ4tbzjCO2J69X8MfjvOTiotF0rNZMjv5UjjNwRR6+ghThcjXvMiIfG+hOXsW+rQyudiayc5YNElVYViPiYfxdoL7vi0EokTHfcS8eGl1ddEuyV72CUIRZzRrDLUOhuyBN5VoLd92rB1uv683TZWWaRguPyPxkpMxoPgpabh7FXKOftuOrcP9a0vL6yNS3e6dKfbc3MxRcBCa2wx9tS/KZ+Qi5MB0zzEcXusca+Akadpr5kyMTAMaoGyPju0/a+sUFhLQq/NM2fQQxMl/5GKGbkx+rlqIm7IJ4c23b0n8ICdSumzMCItIl0ueu8rKFMqqpRueSnQENoD6wSL3zsA8qoqR9LgTwK0dMp1X06ZhSNCL6LAd5rEvvzgFqmrLoqafi7Wz53GU9eb2fHkG8PFslw9RFsjC7wMrG+BfCop40j5Q3XnwnML7KS7fUVd72fSRp/Nrmuql4DqyljcLxmSwCy6WtdLRwnpSTI4lpa4LK/zWdX0nsPUwveMy0vICRpZX9Bn9pMX0BKG6BEfvdsZrweJ1Ow4sb9n3EOh9yrPnrwljA1PkBfpHiP3Ld4UCrtEZiZPGg==
    username: AgCw3YYFu7BPA80A5eWa0bS9JFE5pTk4T2KyPJWDK9KhLeM630lJGjc29w+PvgENxYJSexNIO/bXEVuog8tnSEaP4A+X4itwEiEuUYkEGuaZQJXIPtV/wdf0rBDwXe6YDUirjSQy4rIF1p89e5hcnx8S1WGafoj1cljZL+fHICP0lvt5aqamlEnnTAOPX+ptXbHHF4PgW/ip5dbIxJi2/4L7loxf5M6dx6XPj4klm6ATbj2g7ubVqwtnpnI7N3ixppNHmvFV0xXrRl6h+p9V0NcAJbaSJFXxsY3RGd6HSM6WuCUmTGLYx3CD5bfY9dYTwgfACpLhpVWS6ZpD3IB1CVsr/s9MJ+cMqPWefkE9oRdBRx/QuepYYu4kjhkRIE+cU1TgZObocdfOitPpWKKZFJ6nWQ+q5KoAQzmkgYMn7F2IW6A8jIbF8kk1bFn9q353ISF+DjI2DkTaxrQgU9UXjURCAhwEEUr1xyFYAMRRay/kqNO/GylgS32kSFl4/QdN61riHae05euK2bfy5nJYmV68Ovk1u6qi8YRSGW9xIJOJVBJNh0pLi/u6vF69pSQ6JuILpvo+IYS1yH45Zsao8c0rroSsGvPIfMHA+W03Nn4YpzY5lrwrb/kvbq31ToE73Ode4B2rL9kpdzZIMyG6hUkwJReBqPPvryn/Xoe8+sjTaynNK8Uoyg+Cc6pC116BFcWe2cdWvQ==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: default
