apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: harbor-image-pull-credentials
spec:
  namespaceSelector:
    matchLabels:
      harbor-image-pulls: "true"
  externalSecretSpec:
    refreshInterval: 1h
    secretStoreRef:
      name: vault-secretstore
      kind: ClusterSecretStore
    target:
      name: harbor-credentials
      creationPolicy: Owner
      deletionPolicy: Retain
      type: kubernetes.io/dockerconfigjson
    data:
      - secretKey: .dockerconfigjson
        remoteRef:
          key: harbor/harbor-image-pull-credentials
          property: dockerconfigjson
