apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: harbor-image-pull-credentials
spec:
  namespaceSelector:
    matchLabels:
      harbor-image-pulls: "true"
  externalSecretSpec:
    refreshInterval: 1h
    secretStoreRef:
      name: vault-secretstore
      kind: ClusterSecretStore
    target:
      name: harbor-credentials
      creationPolicy: Owner
      deletionPolicy: Retain
      template:
        engineVersion: v2
        type: kubernetes.io/dockerconfigjson
        data:
          .dockerconfigjson: |-
            {{ $password := .ROBOT_PASSWORD }}
            {{ $username := "robot$image-pull" }}
            {{ $auth := printf "%s:%s" $username $password | b64enc }}
            {"auths":{"harbor.okwilkins.dev":{"username":"{{ $username }}","password":"{{ $password }}","email":"","auth":"{{ $auth }}"}}}
    data:
      - secretKey: ROBOT_PASSWORD
        remoteRef:
          key: harbor/image-pull
          property: ROBOT_PASSWORD
