apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-helm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argocd
      targetRevision: 7.9.0
      helm:
        releaseName: argocd
    - repoURL: https://github.com/okwilkins/h8s
      targetRevision: HEAD
      ref: h8s
    - repoURL: https://github.com/okwilkins/h8s
      targetRevision: HEAD
      path: argocd/environments/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - PruneLast=true
      - ServerSideApply=true
      - CreateNamespace=true
