apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg-resources
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/okwilkins/h8s
    targetRevision: HEAD
    path: cloudnative-pg/environments/prod
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - PruneLast=true
