apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coredns-helm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://coredns.github.io/helm
      chart: coredns
      targetRevision: 1.42.1
      helm:
        releaseName: coredns-home-lan
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - PruneLast=true
      - ServerSideApply=true
