apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-helm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://kubernetes-sigs.github.io/external-dns
      chart: external-dns
      targetRevision: 1.16.1
      helm:
        releaseName: external-dns
        valueFiles:
          - $h8s/external-dns/environments/prod/values.yaml
    - repoURL: https://github.com/okwilkins/h8s
      targetRevision: HEAD
      ref: h8s
    - repoURL: https://github.com/okwilkins/h8s
      targetRevision: HEAD
      path: external-dns/environments/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - PruneLast=true
      - ServerSideApply=true
