apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
  namespace: argocd
  annotations:
    # -1000 so that secrets from important deployments can be created
    argocd.argoproj.io/sync-wave: "-1000"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://charts.external-secrets.io
      chart: external-secrets
      targetRevision: 0.16.2
      helm:
        releaseName: external-secrets
        valueFiles:
          - $h8s/external-secrets-operator/environments/prod/values.yaml
    - repoURL: https://github.com/okwilkins/h8s
      targetRevision: HEAD
      ref: h8s
    - repoURL: https://github.com/okwilkins/h8s
      targetRevision: HEAD
      path: external-secrets-operator/environments/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - PruneLast=true
