apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/kubernetes-sigs/gateway-api
      targetRevision: v1.2.1
      path: config/crd
    - repoURL: https://github.com/kubernetes-sigs/gateway-api
      targetRevision: v1.2.1
      path: config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - PruneLast=true
