apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-operator-helm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: ghcr.io/grafana/helm-charts
      chart: grafana-operator
      targetRevision: v5.17.1
      helm:
        releaseName: grafana-operator
        valueFiles:
          - $h8s/grafana/environments/prod/values.yaml
    - repoURL: https://github.com/okwilkins/h8s
      targetRevision: HEAD
      ref: h8s
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - PruneLast=true
      - ServerSideApply=true
