# https://artifacthub.io/packages/helm/grafana/loki/6.29.0?modal=values

deploymentMode: SingleBinary
loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    ring:
      instance_addr: 127.0.0.1
      kvstore:
        store: inmemory
    type: filesystem
    filesystem:
      directory: /loki
  # https://grafana.com/docs/loki/latest/configuration/#schema_config
  schemaConfig:
    configs:
      - from: 2025-04-01
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
singleBinary:
  replicas: 1
write:
  replicas: 0
read:
  replicas: 0
backend:
  replicas: 0
test:
  enabled: false
lokiCanary:
  enabled: false
gateway:
  enabled: false
# -- DEPRECATED Monitoring section determines which monitoring features to enable, this section is being replaced
# by https://github.com/grafana/meta-monitoring-chart
monitoring:
  serviceMonitor:
    enabled: true
