apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus
  namespace: monitoring
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  datasource:
    name: prom-default
    type: prometheus
    access: proxy
    url: prometheus-stack-kube-prom-prometheus.monitoring.svc.cluster.local:9090
    isDefault: true
    jsonData:
      tlsSkipVerify: true
      timeInterval: 5s
