apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-harbor-prod
spec:
  description: Postgres cluster for the Harbor
  imageName: ghcr.io/cloudnative-pg/postgresql:17.4
  instances: 1
  storage:
    size: 10Gi
  resources:
    requests:
      memory: 512Mi
  managed:
    roles:
      - name: superbaxel
        passwordSecret:
          name: cnpg-harbor-prod-app-user-credentials
          key: password
  enableSuperuserAccess: false
  monitoring:
    enablePodMonitor: true
