apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cnpg-harbor-prod-app-user-credentials
  namespace: harbor
spec:
  encryptedData:
    key2: AgBrj9ZLMFerYFMoXB3kOHdAVpch/iEETtJPLMtDw711mEir/Xkneia03ycw7K2k0nvhzQNg/yHfxasiDIIVUobbR6+5JerQTBAFsK038jv4NBMGpTTnsQPhOt3Xaf2ii4MROg2OVVWw8eKly6LYX3WbGywyOQhWM0xrPCEKCOt2X5eX6kRz1YdTH9mJTQ4gx3m8KlqqLGCtN07vaxjp7Lv8kVXw94Ueys6GQOuYcgjTbvqX1YE3ykuU+K/F/DpdE2nLsRkeGa8HKGjgx+sTTKPZK52pCX31/AYj//mYxTn8e/nwQ+wbv5ldHD/FlpNxoHA6ZIq/Puz41uVbdSMcCwrVz/Cuwakvq93hQrKSYwXe31rzZrdExD9gVNZpES21XYAS9mdhxt1MEEVdzGpMz6GCePEax6ckJZ/Pf/j02W6PnGHPf97FGWMpACtNjMqxABXHSkeN8s7rQtKxFrJMRlD+Qil6otfy6bGM+iBz3Yfuaw5bDQhFMTuyDr3l8Zeo0pvrH0n4g8OFllD50vJCJjhjpv2EjcYn5Mu4fukQj979AvPZGxoz77GiXzTdkpZ9JvfrRp6cCARf3aUxYt6WKY0K082XfAl2M6e+l5uMiYdkueHmKLluCjK9Cn0OKBHMBfehip+7y/vxxKhBMXkISTuKi8gLkgXFLOQvnOlljKCkbXGDm1yKUh2hmjemgxHpmPBmDsmJXejRlRGlz8dnS+SG
    username: AgBUjw6c+/mUGiP3/byg7q0nnWAtb36FRQSqw1l6kg7d+LuRhNv5fwoeBGPpHOu6uZ5AhigUQrS+cpZ1hCm3jOOthDn6//z2RTDGHXf8A6xbM7MxYmpudmYHqJ0s8JhkxIPM9g+a7UhyP4TT/IZvQMP0cj5ExLOlKuJQstnpv87BN23D4lj02bACK4uOc4Un0UxsJKYlcKbPShC4eQ6L5HznOZZXEniFiovVj+3zwRgmqnhBtyqzkOnnBJ7K54+LhEfZaj0DNGu+G+BOmnuIQE08JM1jGNsKQEEFSuHS2oybYMX2CangG/IR+izsDybXh3ZXLG/IkU/IHOn8pZt+sB5hkUJNrOH1heIa0LyE7Z1gRKUG7dJvTmvrfYj0aOmzlllwduxdTLiQGqu0jK/vetqkkJWK/m7UgRapkAKmlJZ/cqJHoDpn/9n5ewIK5TmtSr2MsbruxJ58tR5V4QD8ldHREfeb5I4qDQZUc+q55I9DokmzmF2+ILTDq6W+m1Mgh0HXc4yxwKn0Z2wKQ22sIvDWl9DTegAq8mdqN1AakdKApkewUPopgMFw8zp9zBuE/ICrhsiENTiRWMh8bbdSYSQ67Xty9ACfVv2U7rp7X5VIh1TXT2CKKPCMxOKbFaztdM4NZQLPgWlvYWVZpbGXSMej3ZbARY1AhBF7yCBXeWiyUpP4bF35/IjwYAaP4ZmKSovc9QTWQ2d6qRxP
  template:
    metadata:
      name: cnpg-harbor-prod-app-user-credentials
      namespace: harbor
    type: kubernetes.io/basic-auth
