version: "3"
run: once
includes:
  main:
    taskfile: ../../Taskfile.yaml
    flatten: true
vars:
  IMG_NAME: harbor.okwilkins.dev/main/terraform
tasks:
  push:
    desc: Build and push an image
    preconditions:
      - sh: '[ -n "$TERRAFORM_VER" ]'
        msg: TERRAFORM_VER is empty!
    # This will fail when the builder container doesn't have the CA for harbor.okwilkins.dev!
    vars:
      IMG:
        sh: echo "{{.IMG_NAME}}:${TERRAFORM_VER}"
    cmds:
      - echo "{{.REPO_NAME}}"
      - echo "{{.IMG}}"
      - |
        docker buildx build \
          --platform linux/amd64,linux/arm64 \
          --build-arg TERRAFORM_VER="${TERRAFORM_VER}" \
          -t "{{.IMG}}" \
          --metadata-file /tmp/buildx-metadata.json \
          --push \
          .
      - "echo \"Build completed. Digest: $(jq -r '.\"containerimage.digest\"' /tmp/buildx-metadata.json)\""

  cosign_sign:
    desc: Sign by digest (recursive) to cover all platform manifests
    env:
      COSIGN_PASSWORD: '{{.COSIGN_PASSWORD}}'
      COSIGN_KEY: '{{.COSIGN_KEY}}'
      COSIGN_PUB: '{{.COSIGN_PUB}}'
      DIGEST:
        sh: jq -r '."containerimage.digest"' /tmp/buildx-metadata.json
    vars:
      IMG:
        sh: echo "{{.IMG_NAME}}:${TERRAFORM_VER}"
    cmds:
      - echo "Signing {{.IMG}} @ ${DIGEST}"
      # Bundle and signing flags needed as incompatibility with Cosign v3 and Harbor v2.18
      - |
        cosign sign \
          --new-bundle-format=false \
          --use-signing-config=false \
          --yes \
          --key env://COSIGN_KEY \
          --recursive \
          {{.IMG}}@${DIGEST}

  publish:
    desc: Orchestrate build and signature publishing
    cmds:
      - task: setup_builder
      - task: docker_login
      - task: push
      - task: cosign_sign
