apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-secretstore
spec:
  provider:
    vault:
      server: http://vault-internal.vault.svc.cluster.local:8200
      path: secret
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: external-secrets-vault-auth
          serviceAccountRef:
            name: external-secrets-vault-auth
            namespace: external-secrets
