apiVersion: v1
kind: ConfigMap
metadata:
  name: searxng-settings
  namespace: searxng
data:
  # Go here for full list of settings:
  # https://github.com/searxng/searxng/blob/162c04a1c48333680a76d147f8ae770450d223b8/searx/settings.yml
  settings.yml: |-
    use_default_settings: true

    general:
      debug: false
      instance_name: "Homelab Search"
      privacypolicy_url: false
      donation_url: false
      contact_url: https://www.okwilkins.dev
      enable_metrics: false

    brand:
      new_issue_url: ""
      docs_url: ""
      public_instances: ""
      wiki_url: ""
      issue_url: ""

    search:
      safe_search: 0
      autocomplete: "duckduckgo"
      max_page: 0
      formats:
        - html
        - json

    server:
      port: 8080
      limiter: false
      public_instance: true
      image_proxy: true
      http_protocol_version: "1.1"

    valkey:
      url: "redis://searxng-redis:6379/0"

    engines:
      # Disabled by default (privacy concerns)
      - name: google
        disabled: false
      # CAPTCHA requests too often do disabled
      - name: duckduckgo
        disabled: true
      - name: reddit
        disabled: false
      - name: github
        disabled: false
      # Recommended to enable
      - name: startpage
      - name: qwant
      - name: searx
      - name: wikipedia
      - name: archlinux
      - name: github

