apiVersion: v1
kind: ConfigMap
metadata:
  name: searxng-settings
  namespace: searxng
data:
  # Go here for full list of settings:
  # https://github.com/searxng/searxng/blob/0a118066d/searx/settings.yml
  settings.yml: |-
    use_default_settings:
      engines:
        keep_only:
          - wikipedia
          - wikidata
          - github
          - hackernews
          - google cse

    general:
      debug: false
      instance_name: "Homelab Search"
      privacypolicy_url: false
      donation_url: false
      contact_url: https://www.okwilkins.dev
      enable_metrics: false

    brand:
      new_issue_url: ""
      docs_url: ""
      public_instances: ""
      wiki_url: ""
      issue_url: ""

    search:
      safe_search: 0
      autocomplete: "duckduckgo"
      max_page: 0
      formats:
        - html
        - json

    server:
      port: 8080
      limiter: true
      public_instance: true
      image_proxy: true

    valkey:
      url: "redis://searxng-redis:6379/0"

    engines:
      - name: hackernews
        disabled: false
      - name: mwmbl
        disabled: false
      - name: resulthunter
        disabled: false
