apiVersion: v1
kind: Service
metadata:
  name: searxng-redis
  namespace: searxng
  labels:
    app: searxng-redis
    kubernetes.io/name: searxng-redis
spec:
  type: ClusterIP
  selector:
    app: searxng-redis
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379
