apiVersion: v1
kind: ConfigMap
metadata:
  name: searxng-redis
  namespace: searxng
data:
  redis.conf: |-
    bind 0.0.0.0
    port 6379
    databases 16
    save ""
    appendonly no
    maxmemory 64mb
    maxmemory-policy allkeys-lru

