apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: searxng-secret
  namespace: searxng
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-secretstore
    kind: ClusterSecretStore
  target:
    name: searxng-secret
    creationPolicy: Orphan
    deletionPolicy: Retain
  data:
    - secretKey: SECRET
      remoteRef:
        key: searxng/searxng-secret
        property: SECRET
