apiVersion: batch/v1
kind: CronJob
metadata:
  name: blocklist-updater
spec:
  # Runs daily at 2 AM
  schedule: 0 2 * * *
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          volumes:
            - name: blocklist-storage
              persistentVolumeClaim:
                claimName: coredns-blocklist
          containers:
            - name: updater
              image: curlimages/curl
              command:
                - /bin/sh
                - -c
              args:
                - |
                  BLOCKLIST_PATH="/blocklist/stevenblack-hosts"
                  TEMP_HOSTS_FILE="/tmp/stevenblack-hosts.tmp"
                  STEVENBLACK_URL="https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts"
                  echo "Attempting to download blocklist from $STEVENBLACK_URL"
                  curl -fsSL "$STEVENBLACK_URL" -o "$TEMP_HOSTS_FILE"
                  if [ -s "$TEMP_HOSTS_FILE" ]; then
                      if ! cmp -s "$TEMP_HOSTS_FILE" "$BLOCKLIST_PATH"; then
                          echo "New blocklist downloaded, updating..."
                          mv "$TEMP_HOSTS_FILE" "$BLOCKLIST_PATH"
                          echo "Blocklist updated at $BLOCKLIST_PATH."
                      else
                          echo "Blocklist is already up-to-date."
                          rm "$TEMP_HOSTS_FILE"
                      fi
                  else
                      echo "Failed to download or downloaded an empty blocklist. No changes made."
                      if [ -f "$TEMP_HOSTS_FILE" ]; then
                          rm "$TEMP_HOSTS_FILE"
                      fi
                  fi
              volumeMounts:
                - name: blocklist-storage
                  mountPath: /blocklist
