apiVersion: v1
kind: Service
metadata:
  name: kube-dns
  namespace: kube-system
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9153"
  labels:
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: CoreDNS
    cilium.io/ip-pool-designation: home-lan
    cilium.io/l2-announce-on-lan: "true"
spec:
  selector:
    k8s-app: kube-dns
  clusterIP: 10.96.0.10
  clusterIPs:
    - 10.96.0.10
  ipFamilyPolicy: SingleStack
  ports:
    - name: dns
      port: 53
      protocol: UDP
    - name: dns-tcp
      port: 53
      protocol: TCP
    - name: metrics
      port: 9153
      protocol: TCP
