image:
  registry: harbor.okwilkins.dev/ghcr-cache
  pullSecrets:
    - harbor-credentials

secret:
  additionalSecrets:
    authelia-encryption-key: {}
    cnpg-authelia-prod-app-user-credentials: {}

pod:
  initContainers:
    - name: setup-users-database
      image: harbor.okwilkins.dev/docker-hub-cache/busybox:1.37.0
      command:
        - /bin/sh
        - -c
        - |
          PASSWORD_HASH=$(cat /tmp/password/hash)
          sed "s/PASSWORD_PLACEHOLDER/$PASSWORD_HASH/" /tmp/users_template/users_template.yml > /config/users_database.yml
          echo "Users database created successfully"
      volumeMounts:
        - name: user-password
          mountPath: /tmp/password
          readOnly: true
        - name: users-template
          mountPath: /tmp/users_template
          readOnly: true
        - name: users-config
          mountPath: /config
  extraVolumes:
    - name: user-password
      secret:
        secretName: authelia-user-password
    - name: users-template
      configMap:
        name: authelia-users-template
    - name: users-config
      emptyDir: {}

# https://github.com/authelia/authelia/blob/v4.39.16/config.template.yml
configMap:
  log:
    level: info
  theme: auto

  # TODO: Add metrics
  # telemetry:

  server:
    endpoints:
      authz:
        ext-authz:
          implementation: "ExtAuthz"

  authentication_backend:
    file:
      enabled: true
      path: /config/users_database.yml

  session:
    cookies:
      - domain: okwilkins.dev

  notifier:
    filesystem:
      enabled: true
      filename: /config/notification.txt

  access_control:
    default_policy: two_factor
    rules:
      - domain: "*.okwilkins.dev"
        policy: two_factor

  storage:
    local:
      enabled: false
    postgres:
      enabled: true
      address: 'tcp://cnpg-authelia-prod-rw.authelia.svc.cluster.local:5432'
      database: authelia
      username: authelia
      password:
        disabled: false
        secret_name: cnpg-authelia-prod-app-user-credentials
        path: password
    encryption_key:
      disabled: false
      secret_name: authelia-encryption-key
      path: encryption-key
