apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-oidc-secret
  namespace: argocd
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-secretstore
    kind: ClusterSecretStore
  target:
    name: argocd-oidc-secret
    creationPolicy: Orphan
  data:
    - secretKey: oidc.authelia.clientSecret
      remoteRef:
        key: authelia/argocd-oidc
        property: client-secret-plaintext
