apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - ./keycloak/
  - ./harbor/
  - ./terraform-backend/
patches:
  # Ensure the secret exists before servers
  - patch: |-
      - op: add
        path: /metadata/annotations
        value:
          argocd.argoproj.io/sync-wave: "-1000"
    target:
      group: external-secrets.io
      kind: ExternalSecret
