apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-secretstore
    kind: ClusterSecretStore
  target:
    name: grafana-admin-credentials
    creationPolicy: Orphan
    deletionPolicy: Retain
  data:
    - secretKey: GF_SECURITY_ADMIN_USER
      remoteRef:
        key: grafana/grafana-admin-credentials
        property: GF_SECURITY_ADMIN_USER
    - secretKey: GF_SECURITY_ADMIN_PASSWORD
      remoteRef:
        key: grafana/grafana-admin-credentials
        property: GF_SECURITY_ADMIN_PASSWORD
