apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: etcd-urls
  namespace: external-secrets
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-secretstore
    kind: ClusterSecretStore
  target:
    name: etcd-urls
    creationPolicy: Orphan
    deletionPolicy: Retain
  data:
    - secretKey: URL_1
      remoteRef:
        key: external-secrets/etcd-urls
        property: URL_1
    - secretKey: URL_2
      remoteRef:
        key: external-secrets/etcd-urls
        property: URL_2
