apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: default-policy
spec:
  serviceSelector:
    matchLabels:
      cilium.io/l2-announce-on-lan: "true"
  interfaces:
    - ^enp3s0$
  externalIPs: true
  loadBalancerIPs: true
