apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: default-gateway
  namespace: default
spec:
  gatewayClassName: cilium
  infrastructure:
    annotations:
      io.cilium/lb-ipam-ips: 20.0.0.0
  listeners:
    - protocol: HTTP
      port: 8080
      name: web
      allowedRoutes:
        namespaces:
          from: All
