# https://artifacthub.io/packages/helm/hashicorp/vault/0.4.0?modal=values

server:
  standalone:
    enabled: true
    persistentVolumeClaimRetentionPolicy:
      whenDeleted: Retain
      whenScaled: Retain
    config: |-
      ui = true

      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
        # Enable unauthenticated metrics access (necessary for Prometheus Operator)
        telemetry {
          unauthenticated_metrics_access = "true"
        }
      }
      storage "file" {
        path = "/vault/data"
      }

      telemetry {
        prometheus_retention_time = "30s"
        disable_hostname = true
      }
  ha:
    enabled: false
  dev:
    enabled: false
serverTelemetry:
  serviceMonitor:
    enabled: true
    prometheusRules:
      enabled: true
