apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflows-ui-user-read-only
  namespace: argo-workflows
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-workflows-ui-user-read-only
subjects:
  - kind: ServiceAccount
    name: argo-workflows-ui-user-read-only
    namespace: argo-workflows
