# https://artifacthub.io/packages/helm/argo/argo-workflows/0.45.19?modal=values

singleNamespace: false
controller:
  workflowNamespaces:
    - default
    - dagger-workflows
    - argo-workflows
  metricsConfig:
    enabled: true
  serviceMonitor:
    enabled: true
