# https://artifacthub.io/packages/helm/argo/argo-workflows/0.45.15?modal=values

workflow:
  serviceAccount:
    create: true
controller:
  metricsConfig:
    enabled: true
  serviceMonitor:
    enabled: true
