apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argo-workflows
  namespace: argo-workflows
spec:
  parentRefs:
    - name: default-gateway
      namespace: default
      sectionName: home-lan-argocd
    - name: cloudflare-gateway
      namespace: cloudflare
  hostnames:
    - workflows.okwilkins.dev
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: argo-workflows-helm-server
          port: 2746
