apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harbor-admin-credentials
  namespace: harbor
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: aws-secretstore
    kind: ClusterSecretStore
  target:
    name: harbor-admin-credentials
    creationPolicy: Orphan
    deletionPolicy: Retain
  data:
    - secretKey: username
      remoteRef:
        key: harbor-admin-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: harbor-admin-credentials
        property: password
