apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-admin-credentials
  namespace: harbor
spec:
  encryptedData:
    password: AgA2DKF4v7/sJwLXiZL60xMCHoCjzGU4iV2Fkmadc6G5ozbQDPpKf35ga1v36Qysr2F/13FMdSwGakhwGnaWeF4KoJClW3TgC9OsP9bj9NAz5jKwy3vdzZz58FhCMfqPPH5brMmlWZsjCWRV6gAzsb3DD9KcNNgY8IQ0Zl9c3jswwRCvcF+N83kwrEKKEtm1g/jQ4BLzZtm63XL5crdsVMgxO5oW3A9tSHTCFuJl/GlfKtBowWbhHGDNg1FCVKSGgJLuoctI+8g49sM2Kdz3QJb4Q6FJ/xcu0+AZSNETqO5KD1FQp0tOgH/qeQYI3S0MZqUzmYIiqT04Hg5JwewdAMrGa+C1Prux+QAzfXi2QA6povBShhxmrR6llyOaTRjTG42joNXfms9ondtoPfpmGFOELyjzfRP7I1mUh01ujWQ5CJknoXTwwzdmGQBV2tPB5xv0JPXov+FyJ6MMz9QMNcAm1XgTKc2iP6qRTaIHA/f+Am7PUxJWV8bF3ditD8o0NlqFvoDxN7xQtVKUsEtqLbmbt/aqXZO0fDQ4LoulnsHXTCAHIi1lwt08xu/ZA9EnZ91TesQQN8nS6GrkAP+orniwOHSWw12cALls+hSaUUB1FXcT0gwopcddMpC79yD0AzxszzAASNDTyeVgGVR27FkKN5OmNhC6bfJxoeFPCUK01vPYMAEO2XPbHuZK8DTEZoqmOQdQCKDsoDWD7AyT76qZ
    username: AgClH57TwjXhWhF+6N4GoxEL+YwPoGkvOmY1jvYwSyrY7rq+KWTGPgXrxjHl+DAk3k7MOARaQe8aUHPxnNIxRP6AoCN8Sh+8S4znALlw4hDjsO4NZ8SEqHFwq06EPvXlSTU/Ayyi9/Lu3rrC9aYRJyi+OAdGxrXpJNNfuvWsMwJMecNaoqlTfC868zRdk5hfrotFqhhhXukfvPgkaPJAn5F5k9bDNoGtO9YOXfUX//gJbzwFQiQLAeqcz2/wtIx2duw5CaD0btM4k7s5d5Kh6WAHi3SwT94knoIU2Xw2f94WBEEAx5ABfzu4Kfdw0uNsge/OLmKcaUFglFCOh/fs65HTyBDKXgjdYZ3Lt6HOO1rTghrXgQz6R0mSTSTBWaNax61hXn1iRpjEsNwv9+fas0l6DgL8lpwQKQZivYagcZXRSxA0ptFro5DEsPqd/ff7/w7rG+ohUKeyToWP/TIulqrtguSvilbNaTGeaWhqKi9zjI2weITczEDo3HBSW9tVhJJoyLdVIuuHJqFVdDBR25/UppgDiubbA4/WqNmJniHQ3LrVkJkHFhcpy8hQZbFUb0ZUz9Vf5OaveBYpC1hEIMp99B8ob9ta42QD/RLSQWW4+I3a8kdK0DgYXwBsQgZeWrb/oGafaNNqz/j2gA6fExp+Y6KsV49JRzcAshAPDMesmXFHpNjDlI7fKOaSUYlEdz9WKyPvvQ==
  template:
    metadata:
      name: harbor-admin-credentials
      namespace: harbor
    type: kubernetes.io/basic-auth
