apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harbor-admin-credentials
  namespace: harbor
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-secretstore
    kind: ClusterSecretStore
  target:
    name: harbor-admin-credentials
    creationPolicy: Orphan
    deletionPolicy: Retain
  data:
    - secretKey: username
      remoteRef:
        key: cubbyhole/secret/cnpg/cnpg-harbor-prod-app-user-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: cubbyhole/secret/cnpg/cnpg-harbor-prod-app-user-credentials
        property: password
