# https://artifacthub.io/packages/helm/bitnami/harbor/25.0.0?modal=values

externalURL: https://harbor.okwilkins.dev
expose:
  type: clusterIP
  tls:
    enabled: false
database:
  type: external
  external:
    host: cnpg-harbor-prod-rw.harbor.svc.cluster.local
    port: 5432
    username: superbaxel
    coreDatabase: harbor_core
    existingSecret: cnpg-harbor-prod-app-user-credentials
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
