# https://artifacthub.io/packages/helm/bitnami/harbor/25.0.0?modal=values

externalURL: https://harbor.okwilkins.dev
postgresql:
  enabled: false
externalDatabase:
  host: cnpg-harbor-prod-rw.harbor.svc.cluster.local
  port: 5432
  user: superbaxel
  existingSecret: cnpg-harbor-prod-app-user-credentials
  existingSecretPasswordKey: password
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
