apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-okwilkins-dev
  namespace: argocd
spec:
  secretName: argocd-okwilkins-dev-tls
  issuerRef:
    name: vault-issuer
    kind: ClusterIssuer
  commonName: argocd.okwilkins.dev
  dnsNames:
    - argocd.okwilkins.dev
