apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: draw-okwilkins-dev
  namespace: excalidraw
spec:
  secretName: draw-okwilkins-dev-tls
  issuerRef:
    name: vault-issuer
    kind: ClusterIssuer
  commonName: draw.okwilkins.dev
  dnsNames:
    - draw.okwilkins.dev
