apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-okwilkins-dev
  namespace: monitoring
spec:
  secretName: grafana-okwilkins-dev-tls
  issuerRef:
    name: vault-issuer
    kind: ClusterIssuer
    sectionName: home-lan-argocd
  commonName: grafana.okwilkins.dev
  dnsNames:
    - grafana.okwilkins.dev
