apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor-okwilkins-dev
  namespace: harbor
spec:
  secretName: harbor-okwilkins-dev-tls
  issuerRef:
    name: vault-issuer
    kind: ClusterIssuer
  commonName: harbor.okwilkins.dev
  dnsNames:
    - harbor.okwilkins.dev
