apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-root-ca
  namespace: cert-manager
spec:
  secretName: vault-root-ca
  isCA: true
  commonName: okwilkins.dev
  issuerRef:
    name: vault-issuer
    kind: ClusterIssuer
