apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: terraform-vault-root-ca
  namespace: terraform
spec:
  secretName: terraform-vault-root-ca
  isCA: true
  commonName: okwilkins.dev
  issuerRef:
    name: vault-issuer
    kind: ClusterIssuer
