apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: etcd
  namespace: external-dns
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-secretstore
    kind: ClusterSecretStore
  target:
    name: etcd
    creationPolicy: Orphan
    deletionPolicy: Retain
  data:
    - secretKey: ETCD_URL
      remoteRef:
        key: external-dns/etcd
        property: ETCD_URL
    - secretKey: etcd-ca.crt
      remoteRef:
        key: external-dns/etcd
        property: etcd-ca.crt
    - secretKey: etcd-client.crt
      remoteRef:
        key: external-dns/etcd
        property: etcd-client.crt
    - secretKey: etcd-client.key
      remoteRef:
        key: external-dns/etcd
        property: etcd-client.key
