apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubegrade-scanner
subjects:
  - kind: ServiceAccount
    name: default
    namespace: kubegrade
roleRef:
  kind: ClusterRole
  name: cluster-wide-read
  apiGroup: rbac.authorization.k8s.io
