# https://artifacthub.io/packages/helm/external-dns/external-dns/1.16.1?modal=values

provider:
  # https://github.com/kubernetes-sigs/external-dns/blob/master/charts/external-dns/README.md#providers
  name: coredns
serviceMonitor:
  enabled: true
env:
  - name: ETCD_URLS
    valueFrom:
      secretKeyRef:
        name: etcd-urls
        key: ETCD_FULL_URLS
  - name: ETCD_CA_FILE
    value: /etc/etcd-certs/ETCD_CA
  - name: ETCD_CERT_FILE
    value: /etc/etcd-certs/ETCD_CLIENT_CRT
  - name: ETCD_KEY_FILE
    value: /etc/etcd-certs/ETCD_CLIENT_KEY
extraVolumes:
  - name: etcd-client-certs-volume
    secret:
      secretName: etcd-client-certs
extraVolumeMounts:
  - name: etcd-client-certs-volume
    mountPath: /etc/etcd-certs
    readOnly: true
