apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: images-terraform-workflow
  generateName: images-terraform-
  namespace: dagger-workflows
spec:
  workflowTemplateRef:
    name: dagger-workflow
    namespace: dagger-workflows
  podSpecPatch: |
    containers:
      - name: main
        env:
          - name: HARBOR_ROBOT_TOKEN
            valueFrom:
              secretKeyRef:
                name: harbor-dagger-robot-secret
                key: SECRET
          - name: COSIGN_KEY
            valueFrom:
              secretKeyRef:
                name: cosign-key-pair
                key: cosign.key
          - name: COSIGN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: cosign-key-pair
                key: COSIGN_PASSWORD
  arguments:
    parameters:
      - name: dagger-version
        value: 0.18.12
      - name: dagger-module
        value: https://github.com/kpenfound/greetings-api.git
      - name: git-revision
        value: main
      - name: git-repo
        value: https://github.com/okwilkins/h8s.git
      - name: sub-directory
        value: images/terraform
      - name: terraform-ver
        value: "1.13.5"
      - name: dagger-call-command
        value: |-
          build --src="." \
            --harbor-robot-token="$HARBOR_ROBOT_TOKEN" \
            --cosign-key="$COSIGN_KEY" \
            --cosign-pass="$COSIGN_PASSWORD" \
            --terraform-ver='{{workflow.parameters.terraform-ver}}'
