apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: images-terraform-workflow
  generateName: images-terraform-
  namespace: dagger-workflows
spec:
  workflowTemplateRef:
    name: dagger-workflow
    namespace: dagger-workflows
  arguments:
    parameters:
      - name: dagger-version
        value: 0.8.12
      - name: dagger-module
        value: https://github.com/kpenfound/greetings-api.git
