apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: container-build-terraform-workflow
  generateName: container-build-terraform-
spec:
  entrypoint: main
  templates:
    - name: main
      inputs:
        artifacts:
          - name: source-code
            path: /workspace
            git:
              repo: https://github.com/okwilkins/h8s.git
              revision: main
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      volumes:
        - name: buildah-storage
          emptyDir: {}
      initContainers:
        # Inits VFS compatible dirs for Buildah to use
        - name: init-storage
          image: alpine:latest
          command: ["sh", "-c", "mkdir -p /data/storage /data/storage-run"]
          volumeMounts:
            - name: buildah-storage
              mountPath: /data
      container:
        image: harbor.okwilkins.dev/main/image-buildah:latest
        workingDir: /workspace
        command: ["sh", "-c"]
        args:
          - |
            task publish \
            IMG_NAME=image-buildah \
            TAG="$(git rev-parse --short HEAD)" \
            HARBOR_TOKEN="$HARBOR_TOKEN" \
            COSIGN_PASSWORD="$COSIGN_PASSWORD" \
            COSIGN_KEY="$COSIGN_KEY" \
            COSIGN_PUB="$COSIGN_PUB"
        env:
          - name: STORAGE_DRIVER
            value: "vfs"
          - name: BUILDAH_ISOLATION
            value: "chroot"
          - name: HARBOR_TOKEN
            valueFrom:
              secretKeyRef:
                name: harbor-dagger-robot-secret
                key: SECRET
          - name: COSIGN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: cosign-key-pair
                key: COSIGN_PASSWORD
          - name: COSIGN_KEY
            valueFrom:
              secretKeyRef:
                name: cosign-key-pair
                key: cosign.key
          - name: COSIGN_PUB
            valueFrom:
              secretKeyRef:
                name: cosign-key-pair
                key: cosign.pub
          - name: GIT_CONFIG_PARAMETERS
            value: "'safe.directory=/workspace'"
        volumeMounts:
          - name: buildah-storage
            mountPath: /home/buildah/.local/share/containers
