apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: images-terraform-workflow
  generateName: images-terraform-
  namespace: dagger-workflows
spec:
  workflowTemplateRef:
    name: dagger-workflow
    namespace: dagger-workflows
  arguments:
    parameters:
      - name: dagger-version
        value: 0.18.12
      - name: dagger-module
        value: https://github.com/kpenfound/greetings-api.git
      - name: git-revision
        value: main
      - name: git-repo
        value: https://github.com/okwilkins/h8s.git
      - name: sub-directory
        value: images/terraform
      - name: dagger-call-command
        value: build --src="." --harbor-robot-token=env:HARBOR_ROBOT_TOKEN --cosign-key=env:COSIGN_KEY --cosign-pass=env:COSIGN_PASSWORD --terraform-ver=$TERRAFORM_VER
