apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./images-terraform-workflow.yaml
patches:
  - target:
      group: argoproj.io
      kind: Workflow
    patch: |-
      - op: add
        path: /spec/serviceAccountName
        value: argo-workflow
