# https://artifacthub.io/packages/helm/longhorn/longhorn/1.8.1?modal=values

persistence:
  reclaimPolicy: Retain
  defaultClassReplicaCount: 2
preUpgradeChecker:
  # https://github.com/longhorn/longhorn/issues/8707
  jobEnabled: false
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
